Homework8
OlyaGurt/iosSchool pull request #10
Opened 2023-04-21 11:31 UTC by OlyaGurt

2023-04-29 11:11 UTC, vaganova-ann requested changes
по профилю:
1) собери на se, посмотри, как у тебя кнопка наезжает на коллекцию
2) в CabinetIconCell для bacckgroundCellView не нужны констрейнты ширины и высоты
3) попробуй в LoginLabelCell подставить слишком длинную фразу в лейбл, он выйдет за пределы экрана, нужны констрейнты которые ограничивают лейбл справа и слева
4) для backgroundFieldView не надо задавать ширину, это конфликтует с ее правым и левым констрейнтом
5) думаю что надо положить colorView и dateLabel в стек вью, и в зависимости от данных вью модели скрывать одно из них используя свойство isHidden
6) надо отключить подсветку ячейки при нажатии на нее

по списку локаций: 
7) полосочка разделяющая ячейки должна быть более темная

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetCoordinator.swift
> +
зачем лишняя пустая строчка?

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +        tableView.bottomAnchor.constraint(equalTo: self.bottomAnchor).isActive = true
когда мы верстаем в билдере, то bottomAnchor верхней вью у нас упирается обычно в нижнюю вью, а bottomAnchor нижней вью равен self.bottomAnchor
исходя из этого, надо поправить bottomAnchor для таблицы и кнопки

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +        @objc func backButtonDidTap(sender: UIButton) {
очень большие отступы

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +
пустая строка

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +        if indexPath.row == 0 {
давай ифы заменим на свич

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetViewController.swift
> +        }
отступ

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/Subviews/CabinetIconCell.swift
> +class CabinetIconCell: UITableViewCell {
добавь вью модель, в которой будет передаваться изображение для отображения в обоих UIImageView, добавь функцию update

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/Subviews/CabinetIconCell.swift
> +    @IBOutlet private weak var bacckgroundCellView: UIImageView!
опечатка

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/Subviews/LoginLabelCell.swift
> +class LoginLabelCell: UITableViewCell {
добавь вью модель, в которой будет передаваться юзернейм пользователя и функцию апдейт

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/Subviews/FieldCell.swift
> +    @IBOutlet private weak var backgroundFieldView: UIView!
добавь вью модель, в которой будет передаваться дата и цвет, и что отображаться должно в ячейке, дата или цвет, тогда makeLabel и  makeColorView сольются в одну функцию update

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Cabinet/Subviews/FieldCell.swift
> +        backgroundFieldView.layer.cornerRadius = 15
давай перенесем все содержимое этой функции в инициализатор ячейки

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Location/Subviews/LocationCell.swift
> +        locationLabel.font = .boldSystemFont(ofSize: 18)
задать в интерфейс билдере

2023-04-29 11:11 UTC, vaganova-ann commented on iosSchool/Location/Subviews/LocationCell.swift
> +    @IBOutlet private weak var locationLabel: UILabel!
locationLabel и typeLocationLabel должны иметь правый констрейнт, связывающий их с populationLabel, сейчас у тебя на 14 про макс в последней ячейке текст наезжает на текст

высоту лейблов не нужно задавать, она рассчитывается автоматически

2023-05-06 12:34 UTC, vaganova-ann requested changes
1) в CabinetIconCell у iconView два констрейнта, отвечающие за ось У, наверное одного должно хватить
2) в FieldCell между fieldLabel и stack view должен быть констрейнт

2023-05-06 12:34 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +            let height = UIScreen.main.bounds.height
можно не использовать дополнительную переменную

2023-05-06 12:34 UTC, vaganova-ann commented on iosSchool/Cabinet/CabinetView.swift
> +                    date: "11.10.2000",
потом будешь дату передавать из менеджера, менеджер будет вести во вью контроллер, а данные с вью контроллера во вью будут передаваться во вью модели и там нужно будет создавать вью модели для ячеек

2023-05-07 03:58 UTC, OlyaGurt commented on iosSchool/Cabinet/CabinetView.swift
> +                    date: "11.10.2000",
Хорошо, надо слить домашки

2023-05-07 11:30 UTC, vaganova-ann approved these changes

2023-05-08 10:06 UTC, merged