Homework10
OlyaGurt/iosSchool pull request #12
Opened 2023-04-28 11:53 UTC by OlyaGurt

2023-04-29 10:33 UTC, vaganova-ann requested changes

2023-04-29 10:33 UTC, vaganova-ann commented on iosSchool/Character/CharacterView.swift
> +        collectionView.topAnchor.constraint(equalTo: topAnchor, constant: 59).isActive = true
давай все отступы сделаем не констрейнтами, а либо инсетами, либо в provider

2023-04-29 10:33 UTC, vaganova-ann commented on iosSchool/Character/CharacterView.swift
> +                widthDimension: .estimated(167),
а теперь собери на 14 про макс и поправь ширину для итема и группы обратно)

2023-04-29 10:33 UTC, vaganova-ann commented on iosSchool/Character/Subviews/CharacterCell.swift
> +        self.backgroundColor = UIColor(named: "NewLilac50")
self не нужен
заведи инициализатор ячейки и перенеси туда эти две настройки, функцию makeCell убери

2023-04-29 10:33 UTC, vaganova-ann commented on iosSchool/Character/Subviews/CharacterCell.swift
> +        typeLabel.text = viewModel.type
в typeLabel у нас передается пол и тип существа, сейчас только тип
а еще цвет текста не тот

2023-05-08 12:40 UTC, OlyaGurt commented on iosSchool/Character/Subviews/CharacterCell.swift
> +        typeLabel.text = viewModel.type
Цвет текста появится в develop, после слияния надо будет поправить

2023-05-10 02:36 UTC, vaganova-ann commented on iosSchool/Character/CharacterView.swift
>                  heightDimension: .estimated(167)
надо еще высоту задать absolute здесь и ниже, чтобы потом после загрузок картинок ячейку не растягивало

2023-05-10 02:36 UTC, vaganova-ann commented on iosSchool/Character/Subviews/CharacterCell.swift
> +        self.backgroundColor = UIColor(named: "NewLilac50")
а где

2023-05-10 02:38 UTC, vaganova-ann requested changes

2023-05-10 02:38 UTC, vaganova-ann commented on iosSchool/Character/CharacterView.swift
>                  heightDimension: .estimated(167)
нужно еще здесь и ниже высоту задать абсолютную, чтобы при загрузке фоток ячейку не растягивалос

2023-05-10 03:41 UTC, OlyaGurt commented on iosSchool/Character/Subviews/CharacterCell.swift
> +        self.backgroundColor = UIColor(named: "NewLilac50")
застэшенные изменения пропали :^)

2023-05-10 10:06 UTC, vaganova-ann approved these changes

2023-05-13 10:07 UTC, merged