Homework4
OlyaGurt/iosSchool pull request #6
Opened 2023-04-03 08:49 UTC by OlyaGurt

2023-04-04 03:27 UTC, vaganova-ann requested changes

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Character/CharacterDataProvider.swift
> +        completion: @escaping (Result<Character, ApiError>) -> Void
влезет название функции и ее параметры в одну строчку без ворнинга?

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Character/CharacterView.swift
> +    func updage(with data: CharacterViewData)
опечатка?

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Location/LocationDataProvider.swift
> +        completion: @escaping (Result<LocationsList, ApiError>) -> Void
в одну строчку?

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Responses/ApiClient/CharacterApiClient.swift
> +        onRequestCompleted: @escaping (Result<Character, ApiError>) -> Void
поместится в одну строчку?

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Responses/ApiClient/CharacterApiClient.swift
> +        let url = NetworkConstants.URLStrings.character + "/821"
а может id тогда уже передадим параметром в функцию?

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Responses/ApiClient/RegistrationApiClient.swift
> +            (Result<TokenResponse, ApiError>) ->
что здесь произошло))) кложуру в одну строчку записывать желательно

2023-04-04 03:27 UTC, vaganova-ann commented on iosSchool/Responses/Models/Character.swift
> +    enum CodingKeys: String, CodingKey {
енам тут обязательный или можно без него?

2023-04-04 09:30 UTC, OlyaGurt commented on iosSchool/Character/CharacterDataProvider.swift
> +        completion: @escaping (Result<Character, ApiError>) -> Void
угу

2023-04-04 09:31 UTC, OlyaGurt commented on iosSchool/Character/CharacterView.swift
> +    func updage(with data: CharacterViewData)
да, поправила

2023-04-04 09:32 UTC, OlyaGurt commented on iosSchool/Location/LocationDataProvider.swift
> +        completion: @escaping (Result<LocationsList, ApiError>) -> Void
поправим

2023-04-04 09:34 UTC, OlyaGurt commented on iosSchool/Responses/ApiClient/CharacterApiClient.swift
> +        onRequestCompleted: @escaping (Result<Character, ApiError>) -> Void
да, поправлю

2023-04-04 09:50 UTC, OlyaGurt commented on iosSchool/Responses/ApiClient/CharacterApiClient.swift
> +        let url = NetworkConstants.URLStrings.character + "/821"
да босс

2023-04-04 09:50 UTC, OlyaGurt commented on iosSchool/Responses/ApiClient/RegistrationApiClient.swift
> +            (Result<TokenResponse, ApiError>) ->
х)

2023-04-04 09:57 UTC, OlyaGurt commented on iosSchool/Responses/Models/Character.swift
> +    enum CodingKeys: String, CodingKey {
Снесла

2023-04-05 13:36 UTC, vaganova-ann requested changes

2023-04-05 13:36 UTC, vaganova-ann commented on iosSchool/Responses/ApiClient/RegistrationApiClient.swift
> +        onRequestCompleted: @escaping (Result<TokenResponse, ApiError>) -> Void)
скобка, закрывающая список аргументов, должна быть на следующей строке

2023-04-06 03:53 UTC, OlyaGurt commented on iosSchool/Responses/ApiClient/RegistrationApiClient.swift
> +        onRequestCompleted: @escaping (Result<TokenResponse, ApiError>) -> Void)
поправим

2023-04-06 06:16 UTC, vaganova-ann approved these changes

2023-04-06 06:18 UTC, merged