Homework5
OlyaGurt/iosSchool pull request #7
Opened 2023-04-07 09:56 UTC by OlyaGurt

2023-04-08 08:54 UTC, vaganova-ann requested changes
1) В домашке было указано про вторую кнопку
2) кнопки должны быть закруглены, с границей и тенью
3) текстовые поля должны быть закруглены
4) у иконки должен быть один bottom констрейнт который упирается в кнопки
5) у лейбла Регистрация bottom констрейнт должен упираться в первое текстовое поле
6) у стек вью должен быть один bottom констрейнт который упирается в кнопки
7) у текст филдов есть свойство placeholder, текст "Введите ..." должен быть там, а не в свойстве text, попробуй написать что то в плейсхолдер и сравни
8) исходя из 7, цвет текста надо вернуть на черный
9) собери на se и проверь, что все отображается нормально

2023-04-08 08:54 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +    @IBOutlet private var enterLoginTextField: UITextField!
сделай все weak

2023-04-09 12:53 UTC, OlyaGurt commented on iosSchool/Registration/RegistrationView.swift
> +    @IBOutlet private var enterLoginTextField: UITextField!
Все постаралась поправить

2023-04-10 03:04 UTC, vaganova-ann requested changes
> у иконки должен быть один bottom констрейнт который упирается в кнопки
1) я неверно написала, bottom констрейнт иконки должен упираться в стеквью с текст филдами
2) обводка у кнопок должна быть везде синего цвета, как в дизайне
3) у imageView надо найти и поправить свойство contentMode чтобы на se изображение было без белых полос по бокам

2023-04-10 03:04 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationCoordinator.swift
> +            controller?.present(authVC, animated: true)
Сейчас ты открыла новый вью контроллер авторизации поверх старого вместо того, чтобы закрыть вью контроллер с регистрацией. Оставь кложуру, но ее содержимое надо убрать

2023-04-10 03:04 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationViewController.swift
> +    var onOpenAuth: (() -> Void)?
я бы назвала кложуру closeRegistration

2023-04-10 03:04 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +        enterLoginTextField.text = data.enterLoginTextFielsPlaceholder
у текст филдов есть свойство placeholder, текст "Введите ..." должен быть там, а не в свойстве text, попробуй написать что то в плейсхолдер и сравни

2023-04-10 05:25 UTC, OlyaGurt commented on iosSchool/Registration/RegistrationView.swift
> +        enterLoginTextField.text = data.enterLoginTextFielsPlaceholder
Да, спасибо, поняла наконец про что ты. Гораздо удобнее использовать свойство "placeholder", так как при вводе этот текст пропадает (если оставляем в свойстве "текст", то остается).

2023-04-11 06:56 UTC, vaganova-ann requested changes

2023-04-11 06:56 UTC, vaganova-ann commented on iosSchool/Registration/RegistrationView.swift
> +    @IBOutlet weak var imageView: UIImageView!
забыла private

2023-04-11 07:08 UTC, vaganova-ann approved these changes

2023-04-12 04:29 UTC, merged