Homework7
OlyaGurt/iosSchool pull request #9
Opened 2023-04-15 12:04 UTC by OlyaGurt

2023-04-16 14:49 UTC, vaganova-ann requested changes

2023-04-16 14:49 UTC, vaganova-ann commented on iosSchool/Splash/SplashView.swift
> +    func update(with data: SplashViewData)
а зачем все это? будет работать без метода? а без этого файла?

2023-04-18 04:49 UTC, OlyaGurt commented on iosSchool/Splash/SplashView.swift
> +    func update(with data: SplashViewData)
Да, метод тут не нужен, а вот файл нужен, так как нам нужно передать его во ViewController, чтобы соединить с ксибкой.

2023-04-19 02:14 UTC, vaganova-ann requested changes

2023-04-19 02:14 UTC, vaganova-ann commented on iosSchool/Splash/SplashAssembly.swift
>  import Foundation
давай import Foundation уберем

2023-04-19 02:14 UTC, vaganova-ann commented on iosSchool/Splash/SplashViewController.swift
> +class SplashViewController<View: SplashViewImp>: BaseViewController<View> {
Тут все-таки SplashView нужен

2023-04-20 02:31 UTC, vaganova-ann approved these changes

2023-04-20 10:01 UTC, merged